controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_velocity_controller:
  ros__parameters:
    joints:
      - Revolute_34
      - Revolute_42
      - Revolute_43
      - Revolute_44
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
