# my_robot_controller.yaml

# Define the joint names
joint_names:
  - Revolute_34
  - Revolute_42
  - Revolute_43
  - Revolute_44

# Define the controller parameters
controller:
  type: joint_position_controller/JointPositionController
  joints:
  - Revolute_34
  - Revolute_42
  - Revolute_43
  - Revolute_44
  publish_rate: 50
  gains:
    joint1: {p: 100.0, d: 10.0, i: 0.0, i_clamp: 0.0}
    joint2: {p: 100.0, d: 10.0, i: 0.0, i_clamp: 0.0}
    joint3: {p: 100.0, d: 10.0, i: 0.0, i_clamp: 0.0}
    joint4: {p: 100.0, d: 10.0, i: 0.0, i_clamp: 0.0}
